version: '3.8'

services:
  data-service:
    build:
      context: .
      dockerfile: docker/data-service/Dockerfile
    environment:
      - DATABASE_URL=postgresql://dev_user:dev_pass@db:5432/events
      - FLASK_ENV=development
    ports:
      - "5001:5000"
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./run.py:/app/run.py
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_pass
      - POSTGRES_DB=events
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local 