services:
  data-service:
    build:
      context: .
      dockerfile: docker/data-service/Dockerfile.prod
    environment:
      - DATABASE_URL=${DATABASE_URL}  # From .env file
      - FLASK_APP=src.web:app
      - FLASK_ENV=production
      - API_KEY=${API_KEY}
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --timeout 60 'src.web:app' 